#parameters:
#    categoria.example.class: SON\CategoriaBundle\Example

#services:
#    categoria.example:
#        class: %categoria.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


services:
  categoria_report_manager:
    class: SON\CategoriaBundle\Reporting\CategoriaReportManager
    arguments:
      - "@doctrine.orm.entity_manager"